#!/bin/bash

BREWFILE_PATH="$HOME/Brewfile"

echo "Dumping current Homebrew packages to $BREWFILE_PATH..."
brew bundle dump --file="$BREWFILE_PATH" --force

git --git-dir=$HOME/.cfg/ --work-tree=$HOME add $BREWFILE_PATH
