[window]
padding = { x = 20, y = 40 }
decorations = "Transparent"
opacity = 0.80
blur = true
startup_mode = "Maximized"
title = "Terminal"

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular" }
bold = { family = "FiraCode Nerd Font Mono", style = "Bold" }
italic = { family = "FiraCode Nerd Font Mono", style = "Italic" }
